name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: fim
        run: ./decrypt_secret.sh
      - name : aaaa
        run: cat test.txt
      - name: Test
        run: |
          if [ "$CANDY_SECURE" == "candy" ]
          then
            echo "Got secret"
          fi
          if [ "$PEAR_SECURE" == "pear" ]
          then
            echo "Got secret something else"
          fi
        env: 
          ALE: ${{ secrets.ALE }}
          CANDY_SECURE: ${{ secrets.CANY_APPLE_SECURE }}
          PEAR_SECURE: ${{ secrets.PEAR_MAGIC_SECURE }}
